# data_generation/Dockerfile
FROM python:3.11-slim

WORKDIR /scripts
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
CMD ["python", "generate_strava_data.py"]
